name: 'Get GitLab Project Info'
description: 'Retrieve GitLab project information including API URL, repository URL, and project ID'
inputs:
  gitlab_url:
    description: 'GitLab instance URL'
    required: true
  gitlab_repo_path:
    description: 'GitLab repository path (e.g., group/project)'
    required: true
  gitlab_token:
    description: 'GitLab API access token'
    required: true
outputs:
  project_id:
    description: 'GitLab Project ID'
    value: ${{ steps.get-info.outputs.project_id }}

runs:
  using: "composite"
  steps:
    - id: get-info
      shell: bash
      env:
        GITLAB_URL: ${{ inputs.gitlab_url }}
        GITLAB_REPO_PATH: ${{ inputs.gitlab_repo_path }}
        GITLAB_TOKEN: ${{ inputs.gitlab_token }}
      run: |
        # Construct GitLab API URL and repository URL
        GITLAB_API_URL="${GITLAB_URL}/api/v4"
        
        echo "Attempting to retrieve GitLab Project ID for repository: ${GITLAB_REPO_PATH}"
        
        # Encode the repository path for use in the API URL
        # This is compatible with GitLab 16+ versions
        ENCODED_PATH=$(echo ${GITLAB_REPO_PATH} | sed 's|/|%2F|g')
        
        # Try to get project ID using the encoded path
        # This method uses the project path directly and works on most GitLab versions
        PROJECT_ID=$(curl -s -H "PRIVATE-TOKEN: ${GITLAB_TOKEN}" \
          "${GITLAB_API_URL}/projects/${ENCODED_PATH}" | \
          jq -r '.id')
        
        # If the first approach fails, try using the search API
        if [ -z "$PROJECT_ID" ] || [ "$PROJECT_ID" == "null" ]; then
          echo "First method failed, trying alternative approach with search API..."
          
          # Search for the project by name with exact path
          PROJECT_ID=$(curl -s -H "PRIVATE-TOKEN: ${GITLAB_TOKEN}" \
            "${GITLAB_API_URL}/projects?search=${GITLAB_REPO_PATH}&simple=true" | \
            jq -r '[.[] | select(.path_with_namespace == "'${GITLAB_REPO_PATH}'")] | .[0].id')
        fi
        
        # If both approaches fail, exit with an error
        if [ -z "$PROJECT_ID" ] || [ "$PROJECT_ID" == "null" ]; then
          echo "Error: Unable to retrieve GitLab Project ID. Please check GITLAB_REPO_PATH and GITLAB_TOKEN."
          exit 1
        else
          echo "Successfully retrieved GitLab Project ID: ${PROJECT_ID}"
          echo "project_id=${PROJECT_ID}" >> $GITHUB_OUTPUT
        fi